# Generated by Django 5.1 on 2024-09-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_project_end_date_remove_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=595000000000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects_pics/'),
        ),
    ]
