# Generated by Django 5.1 on 2024-09-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_framework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='evel',
            new_name='level',
        ),
    ]
