# Generated by Django 5.1 on 2024-09-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_evel_framework_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='sada', max_length=500),
            preserve_default=False,
        ),
    ]
